webtalk_init -webtalk_dir D:/XILINX/Vivado/project/8x8_booth3_signed_mult/8x8_booth3_signed_mult.sim/sim_1/behav/xsim/xsim.dir/Booth2_algorithm_signed_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 28 11:04:19 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c4d46f71-5d3d-40be-8607-e47f91f31f1f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b53643cb29ae4429bfe99e23ad0addad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "83" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7520_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3691390148 -regid "" -xml D:/XILINX/Vivado/project/8x8_booth3_signed_mult/8x8_booth3_signed_mult.sim/sim_1/behav/xsim/xsim.dir/Booth2_algorithm_signed_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/XILINX/Vivado/project/8x8_booth3_signed_mult/8x8_booth3_signed_mult.sim/sim_1/behav/xsim/xsim.dir/Booth2_algorithm_signed_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/XILINX/Vivado/project/8x8_booth3_signed_mult/8x8_booth3_signed_mult.sim/sim_1/behav/xsim/xsim.dir/Booth2_algorithm_signed_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
